apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    key: "empty"
spec:
  initContainers:
  - name: web-init
    image: busybox:latest
    command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
    volumeMounts:
    - name: app
      mountPath: /app
  containers:
  - name: web
    image: raventid/raventidweb:second
    volumeMounts:
    - name: app
      mountPath: /app
  volumes:
  - name: app
    emptyDir: {}
